### ISSUE TITLE
Failed to load the lodash-snippets package

### ISSUE THREAD

**Issue by brandom** [richtmat/lodash-snippets#7]
[Enter steps to reproduce below:]

1. Restart & Install Update (Occurs 0.190 => 0.191, but probably other updates as well see richtmat/lodash-snippets#7)

**Atom Version**: 0.191.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [lodash-snippets](https://github.com/richtmat/lodash-snippets) package, v1.1.0

### Stack Trace

Failed to load the lodash-snippets package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/brandon/.atom/packages/lodash-snippets/lib/lodash-snippets-view.coffee:4:199)
  at /Users/brandon/.atom/packages/lodash-snippets/lib/lodash-snippets-view.coffee:5:3
  at Object.<anonymous> (/Users/brandon/.atom/packages/lodash-snippets/lib/lodash-snippets-view.coffee:52:5)
  at Object.<anonymous> (/Users/brandon/.atom/packages/lodash-snippets/lib/lodash-snippets-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/brandon/.atom/packages/lodash-snippets/lib/lodash-snippets.coffee:1:22)
  at Object.<anonymous> (/Users/brandon/.atom/packages/lodash-snippets/lib/lodash-snippets.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:662:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:170:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:161:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:324:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:631:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:54:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "whitespace",
      "pretty-json",
      "turbo-javascript",
      "select-line",
      "git-diff",
      "git-plus"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "bower_components"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-typescript, v2.15.0
autoclose-html, v0.15.0
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
file-icons, v1.5.4
language-ejs, v0.1.0
linter, v0.12.0
lodash-snippets, v1.1.0
monokai, v0.14.0
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by brandom** [comment]
Please note this only seems to occur right after 'Restart and Install Update' from 0.190 to 0.191 - similar to mattberkowitz/autoclose-html#60

**Comment by richtmat** [comment]
thanks @brandom 

I plan to look into it this week.

**Comment by richtmat** [comment]
@brandom I upgraded to atom 1.0 APIs and published 1.1.1, please have a look.

**Comment by brandom** [comment]
@richtmat Awesome. Thanks. Nothing in the deprecation cop :+1: Hopefully no issues on the next 'Restart & Install Update'

**Comment by richtmat** [comment]
Great. Thanks for reporting.
